name: Render Quarto Files

on:
  push:
    paths:
      - '**/*.qmd'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Files
        shell: bash
        run: |
          find . -name "*.qmd" -exec quarto render {} \;
          
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Render Quarto documents" || echo "No changes to commit"
          git push origin
